### ISSUE TITLE
Not Working, Ready to help

### ISSUE THREAD

**Issue by itistripleR** [sabbiriptv/JIO-IPTV#9]
Hi @sabbiriptv I just seen your recent replies regarding you're student and can't able to afford for server, I'm Ready to pay if it has stable access, please let me know, how much it cost, let's see if we can solve the issue, Thanks & Great work BTW, Best wishes for your exams.

**Comment by sabbiriptv** [comment]
Hi There, 

Thank you for reaching out and expressing your willingness to pay for stable access to my server. I appreciate your support and understanding. 

I want to inform you that I currently have hosting available. However, I must admit that I am facing **time constraints**, which makes it challenging for me to maintain everything by myself at the moment. 

Thank you for your kind words and support 💗.
